### PR TITLE
Test skunk with ruby 2.3

### PR DESCRIPTION
**Pull request by etagwerker**
Hey, 

This PR tests `skunk` with Ruby 2.3. I was curious about skunk's compatibility with that version. 

Please check it out.

Thanks!

### CODE REVIEW

**Comment by bronzdoc** [comment]
Is the plan to support a deprecated ruby version for skunk?

**Comment by etagwerker** [comment]
@bronzdoc Considering most of our clients at [FastRuby.io | Rails Upgrade Services](https://fastruby.io) are running a deprecated version of Ruby, yes, I think there would be value in supporting older rubies. Not sure how much time and effort it would take, so this PR is intended to do some research.

**Review by rdormer — APPROVED** [review]

**Comment by bronzdoc** [comment]
@etagwerker the plan is to merge this until the build pass with ruby 2.3? or are we good to go?

**Comment by lubc** [comment]
@etagwerker Looks like the `test-ruby-2-3-x` build is failing. 
I just pushed a blank commit to run the build again (the logs expired in the previous build, and the re-run option was disabled)
Captura de Tela 2021-09-10 às 14 01 01

Were you planning to add support for ruby 2.3 here? Or do you want me to create an issue for that and close this PR?

**Comment by bronzdoc** [comment]
@lubc you can run the build with this button:
Screen Shot 2021-09-13 at 10 52 44 AM

**Comment by bronzdoc** [comment]
We can have this PR just as the setup of circle ci to run the project against 2.3 and we could fix whatever issue we are having in another PR

**Comment by etagwerker** [comment]
@bronzdoc I'm not sure it is worth it to support Ruby 2.3. 

I was trying to figure out how to get the test suite to pass with that version, but there are a lot of dependencies that won't work with Ruby 2.3: 

- SimpleCov 
- Reek
- RubyCritic

So at the end of the day, I'm not sure it is worth the effort...

**Comment by bronzdoc** [comment]
@etagwerker got it, ok. Let's close it, for now, we can revisit it in the future if we believe is worth adding support for ruby 2.3

**Pull request closed without merging**
